TURRET_DATA = [
    {
        "range":100,
        "attack_speed":500,
        "damage":1
    },
    {
        "range":150,
        "attack_speed":250,
        "damage":2
    },
    {
        "range":150,
        "attack_speed":1500,
        "damage":2
    },
    {
        "range":200,
        "attack_speed":1000,
        "damage":4
    },
    {
        "range":125,
        "attack_speed":1000,
        "damage":2
    },
    {
        "range":150,
        "attack_speed":500,
        "damage":3
    }
]
